---
extends: "default"
ignore:
  - "target/**"
rules:
  truthy:
    check-keys: false
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  quoted-strings:
    required: true
    quote-type: "double"
    allow-quoted-quotes: true
